import "server-only";
import type { ProQuestion } from "@/content/questions";

// GermanPass Pro bank — Einbürgerungstest. Original questions written from the
// Basic Law and well-established historical and civic facts; not copied from
// the BAMF question catalogue.
export const germanpassQuestions: ProQuestion[] = [
  // --- Politics in a democracy -----------------------------------------------
  {
    id: "pro-de-pol-1",
    chapter: "politics-and-democracy",
    prompt: "What is the name of Germany's constitution?",
    options: ["The Weimar Constitution", "The Basic Law (Grundgesetz)", "The Federal Charter", "The Civil Code"],
    answer: 1,
    explanation: "Germany's constitution is the Basic Law (Grundgesetz).",
  },
  {
    id: "pro-de-pol-2",
    chapter: "politics-and-democracy",
    prompt: "In which year did the Basic Law come into force?",
    options: ["1945", "1949", "1961", "1990"],
    answer: 1,
    explanation: "The Basic Law came into force in May 1949, founding the Federal Republic of Germany.",
  },
  {
    id: "pro-de-pol-3",
    chapter: "politics-and-democracy",
    prompt: "What does the first sentence of Article 1 of the Basic Law say?",
    options: [
      "All power comes from the people.",
      "Human dignity shall be inviolable.",
      "Germany is a federal state.",
      "All people are equal before the law.",
    ],
    answer: 1,
    explanation: "Article 1 begins: 'Human dignity shall be inviolable.' Protecting it is the duty of all state authority.",
  },
  {
    id: "pro-de-pol-4",
    chapter: "politics-and-democracy",
    prompt: "Who elects the Federal Chancellor?",
    options: ["The people directly", "The Bundestag", "The Bundesrat", "The Federal President alone"],
    answer: 1,
    explanation: "The Federal Chancellor is elected by the Bundestag, on the proposal of the Federal President.",
  },
  {
    id: "pro-de-pol-5",
    chapter: "politics-and-democracy",
    prompt: "Who is Germany's head of state?",
    options: ["The Federal Chancellor", "The Federal President", "The President of the Bundestag", "The Chief Justice"],
    answer: 1,
    explanation:
      "The Federal President (Bundespräsident) is head of state. The Federal Chancellor leads the government.",
  },
  {
    id: "pro-de-pol-6",
    chapter: "politics-and-democracy",
    prompt: "Who elects the Federal President?",
    options: ["The Federal Convention", "The Bundesrat", "The people directly", "The Federal Constitutional Court"],
    answer: 0,
    explanation:
      "The Federal President is elected by the Federal Convention (Bundesversammlung): the members of the Bundestag plus an equal number of delegates from the state parliaments.",
  },
  {
    id: "pro-de-pol-8",
    chapter: "politics-and-democracy",
    prompt: "From what age can German citizens vote in Bundestag elections?",
    options: ["16", "18", "21", "25"],
    answer: 1,
    explanation: "The voting age for Bundestag elections is 18.",
  },
  {
    id: "pro-de-pol-9",
    chapter: "politics-and-democracy",
    prompt: "Which body represents the federal states at the national level?",
    options: ["The Bundestag", "The Bundesrat", "The Federal Convention", "The Federal Cabinet"],
    answer: 1,
    explanation: "The Bundesrat represents the 16 federal states and takes part in federal law-making.",
  },
  {
    id: "pro-de-pol-10",
    chapter: "politics-and-democracy",
    prompt: "What does the 'separation of powers' mean in Germany?",
    options: [
      "The federal states are separate countries",
      "State power is divided between the legislature, the executive and the judiciary",
      "Church and state share power equally",
      "Each party governs for a fixed period",
    ],
    answer: 1,
    explanation:
      "State power is split between law-making (legislature), government and administration (executive) and the courts (judiciary), so each can check the others.",
  },
  {
    id: "pro-de-pol-11",
    chapter: "politics-and-democracy",
    prompt: "Which court can declare a law unconstitutional?",
    options: [
      "The Federal Court of Justice",
      "The Federal Constitutional Court",
      "The European Court of Human Rights",
      "Any local court",
    ],
    answer: 1,
    explanation:
      "The Federal Constitutional Court (Bundesverfassungsgericht) in Karlsruhe decides whether laws are compatible with the Basic Law.",
  },
  {
    id: "pro-de-pol-12",
    chapter: "politics-and-democracy",
    prompt: "Who alone can ban a political party in Germany?",
    options: ["The Federal Chancellor", "The Bundestag", "The Federal Constitutional Court", "The police"],
    answer: 2,
    explanation: "Only the Federal Constitutional Court can declare a party unconstitutional and ban it.",
  },
  {
    id: "pro-de-pol-13",
    chapter: "politics-and-democracy",
    prompt: "Elections in Germany are general, direct, free, equal and…",
    options: ["public", "compulsory", "secret", "online"],
    answer: 2,
    explanation:
      "The Basic Law requires elections to be general, direct, free, equal and secret — nobody may see how you vote.",
  },
  {
    id: "pro-de-pol-14",
    chapter: "politics-and-democracy",
    prompt: "According to the Basic Law, Germany is a democratic and social…",
    options: ["monarchy", "federal state", "republic of cities", "one-party state"],
    answer: 1,
    explanation: "Article 20 describes the Federal Republic of Germany as a democratic and social federal state.",
  },
  {
    id: "pro-de-pol-15",
    chapter: "politics-and-democracy",
    prompt: "Which of these is a basic right protected by the Basic Law?",
    options: [
      "The right to a government job",
      "Freedom of expression",
      "The right not to pay taxes",
      "The right to vote at 14",
    ],
    answer: 1,
    explanation: "Freedom of expression is a basic right, alongside freedom of the press, of religion and of assembly.",
  },

  // --- History and responsibility --------------------------------------------
  {
    id: "pro-de-hist-1",
    chapter: "history",
    prompt: "In which year did the National Socialists come to power in Germany?",
    options: ["1918", "1933", "1939", "1945"],
    answer: 1,
    explanation: "The National Socialists (Nazis) came to power in 1933, when Hitler became Chancellor.",
  },
  {
    id: "pro-de-hist-2",
    chapter: "history",
    prompt: "What happened on 9 November 1938?",
    options: [
      "Germany invaded Poland",
      "The November Pogroms — violent attacks on Jewish people, synagogues and businesses",
      "The Berlin Wall was built",
      "The Basic Law came into force",
    ],
    answer: 1,
    explanation:
      "In the November Pogroms of 1938 the Nazis organised violence against Jewish people across Germany, destroying synagogues, homes and businesses.",
  },
  {
    id: "pro-de-hist-3",
    chapter: "history",
    prompt: "In which year did the Second World War end in Europe?",
    options: ["1918", "1939", "1945", "1949"],
    answer: 2,
    explanation: "The war in Europe ended with Germany's unconditional surrender in May 1945.",
  },
  {
    id: "pro-de-hist-4",
    chapter: "history",
    prompt: "What was the name of the state in eastern Germany from 1949 to 1990?",
    options: [
      "The Federal Republic of Germany",
      "The German Democratic Republic (GDR)",
      "The Weimar Republic",
      "The North German Confederation",
    ],
    answer: 1,
    explanation: "The German Democratic Republic (GDR, or DDR in German) was the socialist state in the east from 1949 to 1990.",
  },
  {
    id: "pro-de-hist-5",
    chapter: "history",
    prompt: "In which year was the Berlin Wall built?",
    options: ["1949", "1953", "1961", "1989"],
    answer: 2,
    explanation: "The GDR began building the Berlin Wall in August 1961.",
  },
  {
    id: "pro-de-hist-6",
    chapter: "history",
    prompt: "On which date did the Berlin Wall fall?",
    options: ["3 October 1990", "9 November 1989", "17 June 1953", "13 August 1961"],
    answer: 1,
    explanation: "The Berlin Wall fell on 9 November 1989, after peaceful protests in the GDR.",
  },
  {
    id: "pro-de-hist-7",
    chapter: "history",
    prompt: "What is celebrated in Germany on 3 October?",
    options: ["Labour Day", "German Unity Day", "Constitution Day", "Remembrance Day"],
    answer: 1,
    explanation: "3 October is German Unity Day, marking reunification in 1990.",
  },
  {
    id: "pro-de-hist-8",
    chapter: "history",
    prompt: "Who was the first Chancellor of the Federal Republic of Germany?",
    options: ["Willy Brandt", "Konrad Adenauer", "Helmut Kohl", "Ludwig Erhard"],
    answer: 1,
    explanation: "Konrad Adenauer was the first Federal Chancellor, from 1949 to 1963.",
  },
  {
    id: "pro-de-hist-9",
    chapter: "history",
    prompt: "Which city was the seat of the West German government before reunification?",
    options: ["Frankfurt am Main", "Bonn", "Munich", "Hamburg"],
    answer: 1,
    explanation: "Bonn was the seat of government of the Federal Republic before reunification. Berlin is now the capital.",
  },
  {
    id: "pro-de-hist-10",
    chapter: "history",
    prompt: "What was the Stasi?",
    options: [
      "The GDR's secret police (Ministry for State Security)",
      "A West German political party",
      "The East German army",
      "A trade union in the GDR",
    ],
    answer: 0,
    explanation: "The Stasi was the GDR's Ministry for State Security — its secret police, which spied on its own citizens.",
  },

  // --- People and society ------------------------------------------------------
  {
    id: "pro-de-soc-1",
    chapter: "society",
    prompt: "In Germany, men and women…",
    options: [
      "have equal rights",
      "have equal rights only at work",
      "have different rights in marriage",
      "have equal rights only after marriage",
    ],
    answer: 0,
    explanation: "The Basic Law states that men and women have equal rights, and the state works to make this real in practice.",
  },
  {
    id: "pro-de-soc-2",
    chapter: "society",
    prompt: "Can a person in Germany be married to more than one person at the same time?",
    options: ["Yes, if all agree", "No", "Yes, with a religious ceremony", "Only abroad"],
    answer: 1,
    explanation: "No. In Germany you may only be married to one person at a time.",
  },
  {
    id: "pro-de-soc-3",
    chapter: "society",
    prompt: "What does freedom of religion mean in Germany?",
    options: [
      "Everyone must belong to a church",
      "You may choose your religion — or have none",
      "Only Christian holidays are allowed",
      "Religion is banned in public",
    ],
    answer: 1,
    explanation: "Freedom of religion means you can practise any religion, change it, or have no religion at all.",
  },
  {
    id: "pro-de-soc-4",
    chapter: "society",
    prompt: "Are parents in Germany allowed to hit their children as a punishment?",
    options: ["Yes, lightly", "Yes, at home", "No, children have a right to a non-violent upbringing", "Only with teachers' agreement"],
    answer: 2,
    explanation: "No. Children in Germany have a legal right to be brought up without violence.",
  },
  {
    id: "pro-de-soc-5",
    chapter: "society",
    prompt: "Is school attendance compulsory for children in Germany?",
    options: ["No, it is optional", "Yes", "Only in cities", "Only for German citizens"],
    answer: 1,
    explanation: "Yes. School attendance is compulsory for all children living in Germany.",
  },
  {
    id: "pro-de-soc-6",
    chapter: "society",
    prompt: "When you move home in Germany, what must you do?",
    options: [
      "Nothing — your new address is updated automatically",
      "Register your new address with the registration office",
      "Tell your employer only",
      "Inform the Bundestag",
    ],
    answer: 1,
    explanation:
      "You must register your new address with the local registration office (Meldebehörde / Bürgeramt), normally within two weeks.",
  },
  {
    id: "pro-de-soc-7",
    chapter: "society",
    prompt: "What is the main role of a trade union in Germany?",
    options: [
      "To collect taxes",
      "To represent employees' interests, for example in wage negotiations",
      "To run the courts",
      "To approve new laws",
    ],
    answer: 1,
    explanation: "Trade unions represent employees and negotiate pay and working conditions with employers.",
  },
  {
    id: "pro-de-soc-8",
    chapter: "society",
    prompt: "Under the Basic Law, may someone be treated worse because of their religion or origin?",
    options: [
      "Yes, in private matters",
      "No, that is prohibited discrimination",
      "Only by employers",
      "Yes, if they are not a citizen",
    ],
    answer: 1,
    explanation:
      "No. The Basic Law forbids disadvantaging anyone because of their sex, origin, race, language, faith or religious or political views.",
  },

  // --- Federal states ---------------------------------------------------------
  {
    id: "pro-de-fed-2",
    chapter: "federal-states",
    prompt: "Which of these is a city-state?",
    options: ["Munich", "Hamburg", "Cologne", "Frankfurt am Main"],
    answer: 1,
    explanation: "Germany has three city-states: Berlin, Hamburg and Bremen.",
  },
  {
    id: "pro-de-fed-3",
    chapter: "federal-states",
    prompt: "Which of these is a German federal state?",
    options: ["Tyrol", "Alsace", "Bavaria", "Silesia"],
    answer: 2,
    explanation: "Bavaria (Bayern) is a German federal state. Tyrol is in Austria and Alsace in France.",
  },
  {
    id: "pro-de-fed-4",
    chapter: "federal-states",
    prompt: "What is the state capital of Hesse?",
    options: ["Frankfurt am Main", "Kassel", "Wiesbaden", "Darmstadt"],
    answer: 2,
    explanation: "Wiesbaden is the capital of Hesse — not Frankfurt, its largest city.",
  },
  {
    id: "pro-de-fed-5",
    chapter: "federal-states",
    prompt: "What is the state capital of North Rhine-Westphalia?",
    options: ["Cologne", "Düsseldorf", "Dortmund", "Essen"],
    answer: 1,
    explanation: "Düsseldorf is the capital of North Rhine-Westphalia, although Cologne is its largest city.",
  },
  {
    id: "pro-de-fed-6",
    chapter: "federal-states",
    prompt: "What is the parliament of a federal state called?",
    options: ["The Bundestag", "The Landtag", "The Bundesrat", "The Stadtrat"],
    answer: 1,
    explanation:
      "Each state elects a Landtag (in the city-states it has another name, such as the Bürgerschaft in Hamburg and Bremen).",
  },
  {
    id: "pro-de-fed-7",
    chapter: "federal-states",
    prompt: "Who leads the government of most federal states?",
    options: ["The Federal Chancellor", "A Minister-President", "The Federal President", "A mayor appointed by Berlin"],
    answer: 1,
    explanation:
      "Most state governments are led by a Minister-President (Ministerpräsident). In the city-states the head of government has a different title, such as Governing Mayor in Berlin.",
  },
  {
    id: "pro-de-fed-8",
    chapter: "federal-states",
    prompt: "Who is mainly responsible for schools in Germany?",
    options: ["The federal government", "The federal states", "The European Union", "Each town's churches"],
    answer: 1,
    explanation: "Education, including schools, is mainly the responsibility of the federal states.",
  },
];
